PKGDIR	?= ../..
L4DIR		?= $(PKGDIR)/../l4re/src/l4

TARGET	= spmm-limits

# list your .c or .cc files here
SRC_C		=
SRC_CC  = main.cc

# list requirements of your program here
REQUIRES_LIBS   =

include $(L4DIR)/mk/prog.mk
