PKGDIR ?= ..
L4DIR	?= $(PKGDIR)/../l4re/src/l4

# create examples demonstrating the use of your package in subdirectories
# and list those subdirs in the TARGET variable.
TARGET = limits

include $(L4DIR)/mk/subdir.mk
